baseURL = "https://how.isdotdot.com/"
languageCode = "en-us"
title = "How Things Work"
paginate = 10

[params]
  siteDescription = "Simple, practical guides explaining how things work and how to do things."
